### ISSUE TITLE
Flatten GeometryCollection into non-complex geometries

### ISSUE THREAD

**Issue by ilyashuma** [felt/geo#133]
I ran into a need to flatten complex `GeometryCollection` into a non-complex `MultiPolygon` geometries.

I'm wondering if there is a place in `geo` for this feature (maybe, `lib/geo/utils.ex`?). Or probably it would be a better fit for https://github.com/pkinney/topo?

I'd be happy to contribute some code, just want to make sure it fits the project needs.

**Comment by s3cur3** [comment]
Hi @ilyashuma! Yeah, I think topo would be a good fit for this. This library hasn't really been in the business of doing transformations aside from encoding & decoding.

Best wishes!
