### ISSUE TITLE
Feature GeoJSON with Geometry object of type GeometryCollection is not supported

### ISSUE THREAD

**Issue by carstenpiepel** [felt/geo#193]
The following valid GeoJSON cannot be decoded:

![image](https://github.com/felt/geo/assets/3856560/f5db146d-1de5-4504-b347-2b0742fce91a)

It fails with the following error:

** (Geo.JSON.Decoder.DecodeError) GeometryCollection is not a valid type
     code: geom = Jason.decode!(json) |> Geo.JSON.decode!()

It appears that the JSON decoder does not support a Feature object that contains a geometry of type GeometryCollection even though it is valid GeoJSON. According to RFC 7946, "a Feature object has a member with the name "geometry".  The value of the geometry member SHALL be either a **Geometry** object as defined above or, in the case that the Feature is unlocated, a JSON null value". A GeometryCollection is a valid Geomtry object, this should be supported.

An example of a real-world web service returning GeoJSON of this kind is the National Weather Service Alert API, e.g. https://api.weather.gov/zones/county/FLC017

**Comment by devBaqar** [comment]
I'm too facing this issue. There is a PR related the mentioned issue. When will it gets merged?

**Comment by s3cur3** [comment]
Merged! Will be released soon as 3.7.0.
