### ISSUE TITLE
ensure_numeric in JSON.Decoder breaks when the string is an integer. not a float

### ISSUE THREAD

**Issue by IceDragon200** [felt/geo#220]
This [commit](https://github.com/felt/geo/commit/9ad50c30ec49ea07549284d85e55e37221525375) introduced a regression where coordinates that exclude their decimal point (i.e. an integer format) are now unable to decode since:
```
iex(1)> String.to_float("12")
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of a float

    :erlang.binary_to_float("12")
    iex:1: (file)
iex(1)> String.to_float("12.0")
12.0
```

**Comment by s3cur3** [comment]
Resolved by #221
